### ISSUE TITLE
Unable to run the usage example

### ISSUE THREAD

**Issue by EuAndreh** [fukamachi/envy#3]
When I ran the code from the `myapp` example, I get `NIL`:
```lisp
(getf (config :myapp.config) :database-type)
; => NIL

(config :myapp.config)
; =>  (:APPLICATION-ROOT #P"/path/to/myapp/")
T
```

Should  this happen? Couldn't figure out.

**Comment by fukamachi** [comment]
I don't get what is the issue in it.

The return value of `config` depends on the value of `APP_ENV`.
As `APP_ENV` is `NIL`, and which means unset, only the `:common` configuration will be used.

**Comment by eudoxia0** [comment]
I think this comes from a misunderstanding I had quite a while ago when I made a PR to Envy.

Envy is for defining sets of configurations which are chosen *on the basis of the value of the environment variable*. If `APP_ENV` is `nil`, `:common` is used, if it's `development` then the `|development|` configuration is used, etc.

**Comment by EuAndreh** [comment]
Sorry for the trouble.
 
Thanks for the clarification.
