### ISSUE TITLE
Example of setting an app's configuration from CLI

### ISSUE THREAD

**Issue by jgarte** [fukamachi/envy#8]
Hi,

Could you give an example of setting an app's configuration from CLI with envy?

It would be much appreciated.

Could we add this to the README?

**Comment by fukamachi** [comment]
Thanks for several PRs.
I don't get what you mean with `from CLI`, but envy switches the configuration settings with a specific environment variable. If I must say, `APP_ENV=development sbcl` runs a REPL process that uses `development` config values.

**Comment by jgarte** [comment]
> Thanks for several PRs. I don't get what you mean with `from CLI`, but envy switches the configuration settings with a specific environment variable. If I must say, `APP_ENV=development sbcl` runs a REPL process that uses `development` config values.

Ah yes, that's what I meant/imagined. Thanks for sharing the example. Just wanted to confirm
